name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - run: npm run compile
      - run: npm test
      - uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}